server:
  port: 8080
  
spring:  jpa:    hibernate:      ddl-auto: none    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234
    driverClassName: org.h2.Driver      
facebook:
  client:
    clientId: 
    clientSecret: 
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me    
